import Form from './Form';
import FormGroup from './FormGroup';
import FormInput from './FormInput';
import FormSelect from './FormSelect';
import FormTextarea from './FormTextarea';
import FormFile from './FormFile';
import FormRange from './FormRange';
import FormPlainText from './FormPlainText';
import FormText from './FormText';
import FormCheck from './FormCheck';
import FormCheckInput from './FormCheckInput';
import FormCheckLabel from './FormCheckLabel';
import FormCheckbox from './FormCheckbox';
import FormRadio from './FormRadio';
import FormFeedback from './FormFeedback';
import FormLabelCol from './FormLabelCol';

Form.Group = FormGroup;
Form.Input = FormInput;
Form.Select = FormSelect;
Form.Textarea = FormTextarea;
Form.File = FormFile;
Form.Range = FormRange;
Form.PlainText = FormPlainText;
Form.Text = FormText;
Form.Check = FormCheck;
Form.CheckInput = FormCheckInput;
Form.CheckLabel = FormCheckLabel;
Form.Checkbox = FormCheckbox;
Form.Radio = FormRadio;
Form.Feedback = FormFeedback;
Form.LabelCol = FormLabelCol;

export default Form;
